spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.0.0.36/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell

#    com.jjsushi.sell.LoggerTest: debug

wechat:
  mpAppId: wxa43b862c395e6042
  mpAppSecret: 6c7949d11ce09805414e5639b32373b5
  mchId:
  mchKey:
  keyPath:
  notifyUrl: