spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 7792347a
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    sentinel:
      host: 10.0.0.36
      port: 6379

server:
  servlet:
    context-path: /sell

#    com.jjsushi.sell.LoggerTest: debug

wechat:
  mpAppId: wxa43b862c395e6042
  mpAppSecret: 6c7949d11ce09805414e5639b32373b5
  mchId:
  mchKey:
  keyPath:
  notifyUrl:

projecturl:
  sell: http://localhost:8080